[tool.poetry]
name = "titanic-backend"
version = "0.1.0"
description = "Flask backend for Titanic project"
authors = ["Titanic Team"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.3"
gunicorn = { version = "^26.1.0", markers = "platform_system != 'Windows'" }
waitress = { version = "3.0.2", markers = "platform_system == 'Windows'" }

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
